services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: dental_clinic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # backend:
  #   build: ./backend
  #   depends_on:
  #     - postgres
  #   environment:
  #     DB_HOST: postgres
  #   ports:
  #     - "8080:8080"

volumes:
  pgdata:
